Repository 2gis/nuclear-vstore, pull requests merged in 2018-06, with the labels that each got.

#170 [AMS-1836] Fix memory allocation of binaries collector
  .gitlab-ci.yml
  build/build.sh
Labels: Worker, bug

#162 [AMS-1122] Redis connection loss handling
  VStore.sln
  src/VStore.Host/Startup.cs
  src/VStore.Host/appsettings.development.json
  src/VStore.Worker/Program.cs
  src/VStore.Worker/VStore.Worker.csproj
  src/VStore/Locks/ReliableRedLockFactory.cs
  src/VStore/Locks/SafeRedLock.cs
  src/VStore/Options/DistributedLockOptions.cs
  src/VStore/Options/DistributedLockOptionsExtensions.cs
Labels: enhancement

#172 Log level increased for ping failed messages in ReliableRedLockFactory
  src/VStore/Locks/ReliableRedLockFactory.cs
Labels: enhancement, redlock
