Repository 2gis/nuclear-vstore, pull requests merged in 2018-04, with the labels that each got.

#156 [AMS-988] code coverage
  .gitlab-ci.yml
  .travis.yml
  readme.md
  src/AmsMigrator/AmsMigrator.csproj
  src/CloningTool/CloningTool.csproj
  src/VStore.Host/Program.cs
  src/VStore.Host/VStore.Host.csproj
  src/VStore.Renderer/VStore.Renderer.csproj
  src/VStore.Worker/VStore.Worker.csproj
  src/VStore/VStore.csproj
  tests/VStore.UnitTests/VStore.UnitTests.csproj
Labels: enhancement

#158 [AMS-478] generate description for Swagger
  src/VStore.Host/Controllers/ObjectsController.cs
  src/VStore.Host/Controllers/SessionsController.cs
  src/VStore.Host/Controllers/TemplatesController.cs
  src/VStore.Host/Startup.cs
  src/VStore.Host/VStore.Host.csproj
  src/VStore.Http.Core/VStore.Http.Core.csproj
  src/VStore.Renderer/Controllers/PreviewController.cs
  src/VStore.Renderer/Controllers/RawsController.cs
  src/VStore.Renderer/Startup.cs
  src/VStore.Renderer/VStore.Renderer.csproj
  src/VStore/S3/MetadataCollectionWrapper.cs
Labels: enhancement

#151 [AMS-1228] template versions listing
  src/VStore.Host/Controllers/TemplatesController.cs
  src/VStore/DataContract/TemplateVersionRecord.cs
  src/VStore/Descriptors/VersionedObjectDescriptor.cs
  src/VStore/Objects/ObjectsStorageReader.cs
  src/VStore/Templates/ITemplatesStorageReader.cs
  src/VStore/Templates/TemplatesStorageReader.cs
Labels: enhancement

#159 update ImageSharp to 1.0.0-dev001134
  NuGet.Config
  src/VStore/VStore.csproj
Labels: bug

#157 [AMS-1509] CloningTool: support placement in template element
  .gitlab-ci.yml
  VStore.sln
  global.json
  src/CloningTool/CloneStrategies/ClonePositionLinks.cs
  src/CloningTool/CloneStrategies/CloneTemplates.cs
  src/CloningTool/CloneStrategies/ReloadFiles.cs
  src/CloningTool/CloningTool.csproj
  src/CloningTool/Json/ApiObjectDescriptorJsonConverter.cs
  src/CloningTool/Json/ApiSerializerSettings.cs
  src/CloningTool/Json/ApiTemplateDescriptor.cs
  src/CloningTool/Json/ApiTemplateDescriptorJsonConverter.cs
  src/CloningTool/Json/ApiTemplateElementDescriptor.cs
  src/CloningTool/Json/ApiTemplateElementDescriptorJsonConverter.cs
  src/CloningTool/Json/ITemplateElementDescriptor.cs
  src/CloningTool/Json/PlacementDescriptor.cs
  src/CloningTool/RestClient/IReadOnlyRestClientFacade.cs
  src/CloningTool/RestClient/IRestClientFacade.cs
  src/CloningTool/RestClient/OkapiClient.cs
  src/VStore.Host/Controllers/ObjectsController.cs
  src/VStore.Host/Startup.cs
  src/VStore.Host/VStore.Host.csproj
  src/VStore.Renderer/VStore.Renderer.csproj
  src/VStore.Worker/VStore.Worker.csproj
  src/VStore/Descriptors/Templates/IGenericTemplateDescriptor.cs
  src/VStore/Descriptors/Templates/ITemplateDescriptor.cs
  src/VStore/Json/BaseTemplateDescriptorJsonConverter.cs
  src/VStore/Json/ElementDescriptorJsonConverter.cs
  src/VStore/Json/ObjectElementPersistenceDescriptorJsonConverter.cs
  src/VStore/Json/TemplateDescriptorJsonConverter.cs
  src/VStore/Json/Tokens.cs
  src/VStore/Objects/IObjectsManagementService.cs
  src/VStore/Objects/ObjectsManagementService.cs
  src/VStore/VStore.csproj
  tests/VStore.UnitTests/HostTests.cs
  tests/VStore.UnitTests/Json/TemplateDeserializationTests.cs
  tests/VStore.UnitTests/VStore.UnitTests.csproj
Labels: cloning tool, enhancement

#161 Move ImageSharp MyGet packages to local lib
  NuGet.Config
  lib/SixLabors.ImageSharp.1.0.0-dev001134.nupkg
  lib/SixLabors.ImageSharp.Drawing.1.0.0-dev001134.nupkg
Labels: workaround
